"""
export_engine.py — Story export to TXT, PDF, and EPUB for The Story Forge.

All functions accept a story dict and a list of chapter dicts and return
raw bytes ready to be sent as a file download.
"""

import io
import textwrap
from datetime import datetime


# ---------------------------------------------------------------------------
# TXT export
# ---------------------------------------------------------------------------

def export_txt(story: dict, chapters: list[dict]) -> bytes:
    """
    Render story + chapters as a plain-text document.

    Returns UTF-8 encoded bytes.
    """
    lines = []

    # ---- Title block ----
    title = story.get("title", "Untitled Story")
    lines.append("=" * 72)
    lines.append(title.center(72))
    lines.append("=" * 72)
    lines.append("")

    genre = story.get("genre", "")
    tone = story.get("tone", "")
    if genre or tone:
        meta = " | ".join(filter(None, [genre, tone]))
        lines.append(meta.center(72))
        lines.append("")

    summary = story.get("summary", "").strip()
    if summary:
        lines.append("Synopsis")
        lines.append("-" * 8)
        # Word-wrap at 72 chars
        for para in summary.split("\n"):
            lines.append(textwrap.fill(para, width=72) if para.strip() else "")
        lines.append("")

    lines.append(
        f"Generated by The Story Forge  |  "
        f"{datetime.utcnow().strftime('%Y-%m-%d')}"
    )
    lines.append("")

    # ---- Chapters ----
    for ch in chapters:
        lines.append("\n" + "─" * 72)
        ch_num = ch.get("chapter_num", "?")
        ch_title = ch.get("title", "").strip()
        if ch_title:
            heading = f"Chapter {ch_num}: {ch_title}"
        else:
            heading = f"Chapter {ch_num}"
        lines.append(heading.center(72))
        lines.append("─" * 72 + "\n")

        content = ch.get("content", "").strip()
        for para in content.split("\n"):
            if para.strip():
                lines.append(textwrap.fill(para, width=72))
            else:
                lines.append("")

        word_count = ch.get("word_count", 0)
        if word_count:
            lines.append(f"\n[{word_count:,} words]")

    lines.append("\n" + "=" * 72)
    lines.append("End of story".center(72))
    lines.append("=" * 72 + "\n")

    return "\n".join(lines).encode("utf-8")


# ---------------------------------------------------------------------------
# PDF export
# ---------------------------------------------------------------------------

def export_pdf(story: dict, chapters: list[dict]) -> bytes:
    """
    Render story + chapters as a nicely formatted PDF.

    Returns raw PDF bytes using ReportLab.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, PageBreak,
        HRFlowable,
    )

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=3 * cm,
        rightMargin=3 * cm,
        topMargin=3 * cm,
        bottomMargin=3 * cm,
        title=story.get("title", "Untitled Story"),
        author="The Story Forge",
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "StoryTitle",
        parent=styles["Title"],
        fontSize=28,
        leading=36,
        alignment=TA_CENTER,
        spaceAfter=12,
        textColor=colors.HexColor("#1a1a2e"),
    )
    subtitle_style = ParagraphStyle(
        "StorySubtitle",
        parent=styles["Normal"],
        fontSize=13,
        leading=18,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#555577"),
        spaceAfter=6,
    )
    synopsis_heading_style = ParagraphStyle(
        "SynopsisHeading",
        parent=styles["Heading2"],
        fontSize=13,
        leading=18,
        spaceAfter=6,
        spaceBefore=18,
        textColor=colors.HexColor("#333355"),
    )
    synopsis_style = ParagraphStyle(
        "Synopsis",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=8,
        textColor=colors.HexColor("#333333"),
    )
    chapter_heading_style = ParagraphStyle(
        "ChapterHeading",
        parent=styles["Heading1"],
        fontSize=18,
        leading=24,
        alignment=TA_LEFT,
        spaceBefore=6,
        spaceAfter=14,
        textColor=colors.HexColor("#1a1a2e"),
    )
    body_style = ParagraphStyle(
        "StoryBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=18,
        alignment=TA_JUSTIFY,
        spaceAfter=8,
        firstLineIndent=18,
        textColor=colors.HexColor("#222222"),
    )
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=9,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#999999"),
    )

    story_title = story.get("title", "Untitled Story")
    genre = story.get("genre", "")
    tone = story.get("tone", "")
    summary = story.get("summary", "").strip()

    elements = []

    # ---- Title page ----
    elements.append(Spacer(1, 3 * cm))
    elements.append(Paragraph(_escape(story_title), title_style))
    elements.append(Spacer(1, 0.4 * cm))

    meta_parts = list(filter(None, [genre, tone]))
    if meta_parts:
        elements.append(Paragraph(_escape(" · ".join(meta_parts)), subtitle_style))

    elements.append(Spacer(1, 0.8 * cm))
    elements.append(
        HRFlowable(width="60%", thickness=1, color=colors.HexColor("#888899"),
                   hAlign="CENTER")
    )
    elements.append(Spacer(1, 0.8 * cm))

    if summary:
        elements.append(Paragraph("Synopsis", synopsis_heading_style))
        for para in summary.split("\n"):
            if para.strip():
                elements.append(Paragraph(_escape(para), synopsis_style))

    elements.append(Spacer(1, 2 * cm))
    date_str = datetime.utcnow().strftime("%B %Y")
    elements.append(
        Paragraph(f"Created with The Story Forge · {date_str}", footer_style)
    )
    elements.append(PageBreak())

    # ---- Chapters ----
    for ch in chapters:
        ch_num = ch.get("chapter_num", "?")
        ch_title = ch.get("title", "").strip()

        if ch_title:
            heading_text = f"Chapter {ch_num}: {ch_title}"
        else:
            heading_text = f"Chapter {ch_num}"

        elements.append(Paragraph(_escape(heading_text), chapter_heading_style))
        elements.append(
            HRFlowable(width="100%", thickness=0.5,
                       color=colors.HexColor("#ccccdd"))
        )
        elements.append(Spacer(1, 0.4 * cm))

        content = ch.get("content", "").strip()
        for para in content.split("\n"):
            if para.strip():
                elements.append(Paragraph(_escape(para), body_style))
            else:
                elements.append(Spacer(1, 0.2 * cm))

        word_count = ch.get("word_count", 0)
        if word_count:
            elements.append(Spacer(1, 0.4 * cm))
            elements.append(
                Paragraph(f"[{word_count:,} words]", footer_style)
            )

        elements.append(PageBreak())

    doc.build(elements)
    return buffer.getvalue()


def _escape(text: str) -> str:
    """Escape characters that ReportLab Paragraph can't handle raw."""
    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


# ---------------------------------------------------------------------------
# EPUB export
# ---------------------------------------------------------------------------

def export_epub(story: dict, chapters: list[dict]) -> bytes:
    """
    Render story + chapters as an EPUB 2 e-book.

    Returns raw EPUB bytes using ebooklib.
    """
    from ebooklib import epub

    book = epub.EpubBook()

    story_title = story.get("title", "Untitled Story")
    genre = story.get("genre", "")
    summary = story.get("summary", "").strip()

    book.set_identifier(f"storyforge-{story.get('id', 'unknown')}")
    book.set_title(story_title)
    book.set_language("en")
    book.add_author("The Story Forge")

    if genre:
        book.add_metadata("DC", "subject", genre)
    if summary:
        book.add_metadata("DC", "description", summary)

    # ---- CSS ----
    css_content = """
body {
    font-family: Georgia, 'Times New Roman', serif;
    font-size: 1em;
    line-height: 1.7;
    margin: 1em 1.5em;
    color: #222;
}
h1.book-title {
    font-size: 2em;
    text-align: center;
    margin-top: 2em;
    color: #1a1a2e;
}
h2.subtitle {
    font-size: 1em;
    text-align: center;
    color: #666;
    margin-top: 0.5em;
}
p.synopsis-label {
    font-variant: small-caps;
    font-weight: bold;
    margin-top: 2em;
    color: #444;
}
p.synopsis {
    font-style: italic;
    color: #333;
}
h2.chapter-title {
    font-size: 1.5em;
    margin-top: 2em;
    margin-bottom: 0.5em;
    color: #1a1a2e;
    page-break-before: always;
}
p {
    text-indent: 1.2em;
    margin: 0 0 0.4em 0;
}
p.no-indent {
    text-indent: 0;
}
p.word-count {
    font-size: 0.8em;
    color: #999;
    text-align: right;
    margin-top: 1em;
    text-indent: 0;
}
hr {
    border: none;
    border-top: 1px solid #ccc;
    margin: 1.5em auto;
    width: 60%;
}
"""
    nav_css = epub.EpubItem(
        uid="style_nav",
        file_name="style/nav.css",
        media_type="text/css",
        content=css_content,
    )
    book.add_item(nav_css)

    # ---- Title / intro page ----
    meta_parts = list(filter(None, [genre, story.get("tone", "")]))
    meta_str = " · ".join(meta_parts)

    intro_html = f"""<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.1//EN'
  'http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
<head>
  <title>{_html_escape(story_title)}</title>
  <link rel='stylesheet' type='text/css' href='style/nav.css'/>
</head>
<body>
  <h1 class='book-title'>{_html_escape(story_title)}</h1>
  {f"<h2 class='subtitle'>{_html_escape(meta_str)}</h2>" if meta_str else ""}
  <hr/>
  {_synopsis_html(summary)}
  <p class='no-indent' style='text-align:center;margin-top:3em;color:#999;font-size:0.85em;'>
    Created with The Story Forge
  </p>
</body>
</html>"""

    intro_item = epub.EpubHtml(
        title="Title Page",
        file_name="intro.xhtml",
        lang="en",
    )
    intro_item.content = intro_html
    intro_item.add_item(nav_css)
    book.add_item(intro_item)

    # ---- Chapter pages ----
    epub_chapters = [intro_item]
    spine = ["nav", intro_item]

    for ch in chapters:
        ch_num = ch.get("chapter_num", "?")
        ch_title = ch.get("title", "").strip()
        content = ch.get("content", "").strip()
        word_count = ch.get("word_count", 0)

        if ch_title:
            heading = f"Chapter {ch_num}: {ch_title}"
        else:
            heading = f"Chapter {ch_num}"

        # Convert paragraphs to <p> tags
        paras_html = "\n".join(
            f"  <p>{_html_escape(p)}</p>"
            for p in content.split("\n")
            if p.strip()
        )

        wc_html = (
            f"<p class='word-count'>[{word_count:,} words]</p>"
            if word_count else ""
        )

        ch_html = f"""<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.1//EN'
  'http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
<head>
  <title>{_html_escape(heading)}</title>
  <link rel='stylesheet' type='text/css' href='style/nav.css'/>
</head>
<body>
  <h2 class='chapter-title'>{_html_escape(heading)}</h2>
{paras_html}
{wc_html}
</body>
</html>"""

        ch_item = epub.EpubHtml(
            title=heading,
            file_name=f"chapter_{ch_num:03d}.xhtml",
            lang="en",
        )
        ch_item.content = ch_html
        ch_item.add_item(nav_css)
        book.add_item(ch_item)
        epub_chapters.append(ch_item)
        spine.append(ch_item)

    # ---- ToC and spine ----
    book.toc = [epub.Link(item.file_name, item.title, item.id)
                for item in epub_chapters]
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = spine

    # Write to bytes buffer
    buffer = io.BytesIO()
    epub.write_epub(buffer, book, {})
    return buffer.getvalue()


def _html_escape(text: str) -> str:
    """Minimal HTML entity escaping for EPUB content."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


def _synopsis_html(summary: str) -> str:
    """Render synopsis paragraphs as HTML, or empty string if blank."""
    if not summary.strip():
        return ""
    paras = "\n".join(
        f"  <p class='synopsis'>{_html_escape(p)}</p>"
        for p in summary.split("\n")
        if p.strip()
    )
    return f"<p class='synopsis-label'>Synopsis</p>\n{paras}"
